name: Réalisation des tests unitaires


on: 
  pull_request:
    types: [closed]

jobs: 
  ifWindows:
    runs-on: macos-latest
    steps: 
      - name: IF Windows
        run: echo "L'os présent sur le runner est ${{ runner.os }}"

  
