name: Réalisation des tests unitaires


on: 
  pull_request:
    branches:
      - main

jobs: 
  ifWindows:
    runs-on: macos-latest
    steps: 
      - name: IF Windows
        run: echo "Pull request fermée"

  
